### ISSUE TITLE
Does CVTREE have a limit on the number of genomes？

### ISSUE THREAD

**Issue by chuanfaliu** [ghzuo/CVTree#9]
Hi, prof. Zuo. I am trying to use cvtree to build a big tree base on about 89,000. all the genomes are fna formats. Currently. when I run: cvtree -G genomes -g faa -i list
I met an error: 
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_fill_insert
Aborted (core dumped)

I did not use docker due to the limit of authority. 
Could you help me out about that.
Any suggestions for me are appreciated.
Thanks a lot for your help.

**Comment by ghzuo** [comment]
Hi, Prof. Liu

There is not limit on number of genomes in code of CVTree.
As the error message, it seems that some vector is too long (I guess it is the distance matrix).
I had use it to perform project with about 20000 genomes. 
Your project is about 5 time of it, so huge memory for the computer is required.
I will check on my computer server with big memory later.

**Comment by chuanfaliu** [comment]
Glad to hear from you, Prof Zuo. I have a serve with ~ 1.8T memory.  Is it possible to perform this analysis based on your valuable experience? Thank you so much.

**Comment by ghzuo** [comment]
It is enough. As the error report, the problem is caused by the length of vector. I only check the progrom on my 512G before. There are two big vectors in the program. I need some testing to find which vector is too length and fix it. I am out of my office. I will reply later.


As a template suggestion, you can try to limit the memory in <500G by the -M option. It will affect the performance of the program but not the result.

**Comment by chuanfaliu** [comment]
I test 
1) cvtree -G genomes -g fna -i test_list_30000_genomes -M 500
2) cvtree -G genomes -g fna -i test_list_45000_genomes -M 1500
but failed when test:
cvtree -G genomes -g fna -i test_list_46000_genomes -M 1500

I also found this task did not take up too much memory (less than 100 G) when I test 46000 genomes at the beginning.

error massage:
cvtree -G genomes -g fna -i test_list1 -M 1500
*** The dimension of the distance matrix is: 46000
*** All 1057977000 distances are blank for K=5, Time Elapsed: 34.832 s
*** The dimension of the distance matrix is: 46000
*** All 1057977000 distances are blank for K=6, Time Elapsed: 59.224 s
*** The dimension of the distance matrix is: 46000
*** All 1057977000 distances are blank for K=7, Time Elapsed: 83.843 s
*** Start check and calculate CVs for 46000 Genomes, Time Elapsed: 83.843 s
*** CV Section: All CVs are obtained, Time Elapsed: 442.145 s
*** Start calculate distance for K=5, Time Elapsed: 442.145 s
    *** Start the calculate step 1
    *** 30000/30000 CVs will be resident in memory,
    *** which size is 0.457705G, Time Elapsed: 455.919 s
        *** Complete read CVs, Time Elapsed: 456.133 s

*** CV Section: All CVs are obtained, Time Elapsed: 455.167 s
*** Start calculate distance for K=5, Time Elapsed: 455.167 s
    *** Start the calculate step 1
    *** 46000/46000 CVs will be resident in memory,
    *** which size is 0.701845G, Time Elapsed: 492.61 s
        *** Complete read CVs, Time Elapsed: 495.713 s
[1]+  Segmentation fault      (core dumped) cvtree -G genomes -g fna -i test_list -M 1500
Segmentation fault (core dumped)

**Comment by ghzuo** [comment]
I had fixed the problem caused by the big number of genomes.   I had tested the program with 100000 small sequences on my computer. It's workable. Now, You can download new code from github and recompiled. 

The problem is caused by the number of elements was out the range of int. I had changed int to long, and also add new file format to save the distance matrix. Please don't use NetCDF format to save distance matrix. There are some number limit in its write api in my testing. HDF5 is the best choice. If your computer does not support HDF5, use the gzip format.

**Comment by chuanfaliu** [comment]
Thank you for fixing that. cheers!
